// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkNJ9wglpB_SX86BHjVIY9mAHZklLfJWY',
    appId: '1:422516822490:web:597364602a6046802f70e3',
    messagingSenderId: '422516822490',
    projectId: 'baytak-1c380',
    authDomain: 'baytak-1c380.firebaseapp.com',
    storageBucket: 'baytak-1c380.firebasestorage.app',
    measurementId: 'G-MRK2B4TVMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkBFmLcCi_iCgM6_VPbjBEU9bnEtZfmu0',
    appId: '1:422516822490:android:aceab33d3ed5e4c82f70e3',
    messagingSenderId: '422516822490',
    projectId: 'baytak-1c380',
    storageBucket: 'baytak-1c380.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIWJdG9icUu4zTJw-apZzrCJ9Cjbu0lzg',
    appId: '1:422516822490:ios:2181e7883d9a25192f70e3',
    messagingSenderId: '422516822490',
    projectId: 'baytak-1c380',
    storageBucket: 'baytak-1c380.firebasestorage.app',
    iosBundleId: 'com.example.baytak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIWJdG9icUu4zTJw-apZzrCJ9Cjbu0lzg',
    appId: '1:422516822490:ios:2181e7883d9a25192f70e3',
    messagingSenderId: '422516822490',
    projectId: 'baytak-1c380',
    storageBucket: 'baytak-1c380.firebasestorage.app',
    iosBundleId: 'com.example.baytak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkNJ9wglpB_SX86BHjVIY9mAHZklLfJWY',
    appId: '1:422516822490:web:6fa4ac09db7b19332f70e3',
    messagingSenderId: '422516822490',
    projectId: 'baytak-1c380',
    authDomain: 'baytak-1c380.firebaseapp.com',
    storageBucket: 'baytak-1c380.firebasestorage.app',
    measurementId: 'G-Z208T967P8',
  );
}
