// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKZ-1rqIPiGvlD8BRXj2nTfKB3r3bGsJA',
    appId: '1:916053568733:web:f6eae8e5658814959c3f34',
    messagingSenderId: '916053568733',
    projectId: 'baytak-36ccd',
    authDomain: 'baytak-36ccd.firebaseapp.com',
    storageBucket: 'baytak-36ccd.firebasestorage.app',
    measurementId: 'G-LXEPNMJKQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoK_uz6CXw2R3yJGe19aZljrLSj22f9Mc',
    appId: '1:916053568733:android:fd380597237e983c9c3f34',
    messagingSenderId: '916053568733',
    projectId: 'baytak-36ccd',
    storageBucket: 'baytak-36ccd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7DHTuiNzh8ZxotrHvZwnVibYwLV39psc',
    appId: '1:916053568733:ios:06b4ea3c700f067a9c3f34',
    messagingSenderId: '916053568733',
    projectId: 'baytak-36ccd',
    storageBucket: 'baytak-36ccd.firebasestorage.app',
    iosBundleId: 'com.example.baytak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7DHTuiNzh8ZxotrHvZwnVibYwLV39psc',
    appId: '1:916053568733:ios:06b4ea3c700f067a9c3f34',
    messagingSenderId: '916053568733',
    projectId: 'baytak-36ccd',
    storageBucket: 'baytak-36ccd.firebasestorage.app',
    iosBundleId: 'com.example.baytak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKZ-1rqIPiGvlD8BRXj2nTfKB3r3bGsJA',
    appId: '1:916053568733:web:d4f04fadfce68dd09c3f34',
    messagingSenderId: '916053568733',
    projectId: 'baytak-36ccd',
    authDomain: 'baytak-36ccd.firebaseapp.com',
    storageBucket: 'baytak-36ccd.firebasestorage.app',
    measurementId: 'G-2KC4H04MFF',
  );
}
